services:
  slic3r-api:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    command: /bin/bash -c "cd /src && go run ./cmd"
    volumes:
      - ../:/src
      - ../configs:/configs
    environment:
      - PORT=3030
      - HOST=0.0.0.0 
      - CONFIGS=/configs/ 
    ports:
      - 3030:3030